config/routes.rb
Task::Application.routes.draw do
  get "home/index"

  root :to => 'home#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  #controller method which accepts the parameters and processes to generate the output
  def index
    if params[:n_value].present? && params[:k_value].present?
      #parsing the parameters and casting them to integer
      n = params[:n_value].to_i
      k = params[:k_value].to_i
      total = 0
      @result = []    #resultset object which is used to display the output
      if(n>0 )
        if(k>0 && k<=n)
          for i in 1..(n-2)
            for j in i..(n-1-i)
              k= n-i-j
              if(k>=j)
                total = total+1
                @result << "#{i} + #{j} + #{k} = #{n}"      #the unique equation strings to be displayed are pushed to the resultset object
              end
            end
          end
        end
      end
    else
      @result = nil     #if the resultset is nil
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_result.html.erb
<!-- the content of the result to be displayed -->

<% if @result.nil? %>
  <h3>Please provide the required inputs</h3>   <!-- the content to be displayed if the given input are not valid -->
<% else %>
  <% if @result.empty? %>
    <h3>There are no solutions for the given input</h3>   <!-- the content to be displayed if there are no solutions for the given input -->
  <% else %>
  <h3>The Unique solution for the given Input are:</h3>   <!-- the content to be displayed if there are solutions for the given input -->
  
  <% @result.each do |res| %>             <!-- iterating through the result set to display the results -->       
    <%= res %><br />
  <% end %>
  <% end %>
<% end %>

app/views/home/index.html.erb
<h2>Simple Form</h2>
<!-- A simple form to take the inputs -->
<%= form_tag home_index_path, :method => :get, :remote => true do %>
  <%= text_field_tag "n_value", "", :placeholder => "n value", :value => params[:n_value] %> <!-- input field to take the n value -->
  <%= text_field_tag "k_value", "", :placeholder => "k value", :value => params[:k_value] %> <!-- input field to take the k value -->
  <%= submit_tag 'Results' %>
<% end %>

<div id="result"></div>  <!-- div container to place the result set after processing ->

app/views/home/index.js.erb
$("#result").html("<%= j render 'result' %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Task</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>